
INSERT INTO permissions (
    name, description, created_at, updated_at, created_by, last_updated_by, deleted
)
VALUES

-- Organization
('ORGANIZATION_READ', 'View organization information.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('ORGANIZATION_CREATE', 'Create organizations.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('ORGANIZATION_UPDATE', 'Update organization information.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('ORGANIZATION_DELETE', 'Delete organizations.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('ORGANIZATION_RESTORE', 'Restore deleted organizations.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('ORGANIZATION_SETTINGS_READ', 'View organization settings.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('ORGANIZATION_SETTINGS_UPDATE', 'Update organization settings.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),

-- User
('USER_READ', 'View user information.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('USER_CREATE', 'Create users.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('USER_UPDATE', 'Update user information.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('USER_DELETE', 'Delete users.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('USER_RESTORE', 'Restore deleted users.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('USER_ACTIVATE', 'Activate user accounts.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('USER_DEACTIVATE', 'Deactivate user accounts.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('USER_ACCESS_REVIEW', 'Review user access and assigned roles.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),

-- Role
('ROLE_READ', 'View roles.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('ROLE_CREATE', 'Create roles.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('ROLE_UPDATE', 'Update roles.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('ROLE_DELETE', 'Delete roles.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('ROLE_RESTORE', 'Restore deleted roles.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('ROLE_ASSIGN', 'Assign roles to users.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('ROLE_UNASSIGN', 'Remove roles from users.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),

-- Permission
('PERMISSION_READ', 'View available permissions.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),

-- Supplier
('SUPPLIER_READ', 'View supplier information.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('SUPPLIER_CREATE', 'Create suppliers.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('SUPPLIER_UPDATE', 'Update supplier information.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('SUPPLIER_DELETE', 'Delete suppliers.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('SUPPLIER_RESTORE', 'Restore deleted suppliers.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('SUPPLIER_CONTACT_READ', 'View supplier contact information.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('SUPPLIER_CONTACT_MANAGE', 'Manage supplier contacts.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('SUPPLIER_CATEGORY_READ', 'View supplier categories.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('SUPPLIER_CATEGORY_MANAGE', 'Manage supplier categories.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('SUPPLIER_TAX_READ', 'View supplier tax information.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('SUPPLIER_TAX_UPDATE', 'Update supplier tax information.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('SUPPLIER_BILLING_READ', 'View supplier billing information.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('SUPPLIER_BILLING_UPDATE', 'Update supplier billing information.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('SUPPLIER_PERFORMANCE_READ', 'View supplier performance information.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('SUPPLIER_RISK_READ', 'View supplier risk information.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('SUPPLIER_RISK_UPDATE', 'Update supplier risk information.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('SUPPLIER_DOCUMENT_READ', 'View supplier documents.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('SUPPLIER_DOCUMENT_MANAGE', 'Manage supplier documents.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),

-- Product
('PRODUCT_READ', 'View product information.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('PRODUCT_CREATE', 'Create products.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('PRODUCT_UPDATE', 'Update product information.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('PRODUCT_DELETE', 'Delete products.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('PRODUCT_RESTORE', 'Restore deleted products.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('PRODUCT_ACTIVATE', 'Activate products.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('PRODUCT_DEACTIVATE', 'Deactivate products.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('PRODUCT_CATEGORY_READ', 'View product categories.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('PRODUCT_CATEGORY_MANAGE', 'Manage product categories.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('PRODUCT_UNIT_READ', 'View product units.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('PRODUCT_UNIT_MANAGE', 'Manage product units.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('PRODUCT_SUPPLIER_READ', 'View supplier-product relationships.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('PRODUCT_SUPPLIER_MANAGE', 'Manage supplier-product relationships.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('PRODUCT_PRICE_READ', 'View product pricing information.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('PRODUCT_PRICE_UPDATE', 'Update product pricing information.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('PRODUCT_TAX_READ', 'View product tax information.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('PRODUCT_TAX_UPDATE', 'Update product tax information.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('PRODUCT_REORDER_THRESHOLD_READ', 'View product reorder thresholds.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('PRODUCT_REORDER_THRESHOLD_UPDATE', 'Update product reorder thresholds.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),

-- Purchase Request
('PURCHASE_REQUEST_READ', 'View purchase requests.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('PURCHASE_REQUEST_CREATE', 'Create purchase requests.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('PURCHASE_REQUEST_UPDATE', 'Update purchase requests.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('PURCHASE_REQUEST_DELETE', 'Delete purchase requests.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('PURCHASE_REQUEST_SUBMIT', 'Submit purchase requests.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('PURCHASE_REQUEST_CANCEL', 'Cancel purchase requests.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('PURCHASE_REQUEST_STATUS_UPDATE', 'Update purchase request status.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),

-- Purchase Order
('PURCHASE_ORDER_READ', 'View purchase orders.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('PURCHASE_ORDER_CREATE', 'Create purchase orders.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('PURCHASE_ORDER_UPDATE', 'Update purchase orders.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('PURCHASE_ORDER_DELETE', 'Delete purchase orders.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('PURCHASE_ORDER_SUBMIT', 'Submit purchase orders.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('PURCHASE_ORDER_CANCEL', 'Cancel purchase orders.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('PURCHASE_ORDER_STATUS_UPDATE', 'Update purchase order status.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('PURCHASE_ORDER_SUPPLIER_CHANGE', 'Change the supplier of a purchase order.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),

-- Approval
('APPROVAL_READ', 'View approval tasks and requests.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('APPROVAL_APPROVE', 'Approve approval requests.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('APPROVAL_REJECT', 'Reject approval requests.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('APPROVAL_ESCALATE', 'Escalate approval requests.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('APPROVAL_CANCEL', 'Cancel approval requests.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('APPROVAL_RULE_READ', 'View approval rules.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('APPROVAL_RULE_CREATE', 'Create approval rules.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('APPROVAL_RULE_UPDATE', 'Update approval rules.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('APPROVAL_RULE_DELETE', 'Delete approval rules.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('APPROVAL_HISTORY_READ', 'View approval history.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),

-- Inventory
('INVENTORY_READ', 'View inventory information.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('INVENTORY_UPDATE', 'Update inventory information.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('INVENTORY_RESERVATION_READ', 'View inventory reservations.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('INVENTORY_RESERVE', 'Reserve inventory.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('INVENTORY_RELEASE', 'Release inventory reservations.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('INVENTORY_RECEIPT_READ', 'View inventory receipts.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('INVENTORY_RECEIPT_CREATE', 'Create inventory receipts.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('INVENTORY_ADJUSTMENT_READ', 'View inventory adjustments.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('INVENTORY_ADJUSTMENT_CREATE', 'Create inventory adjustments.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('INVENTORY_TRANSFER_READ', 'View inventory transfers.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('INVENTORY_TRANSFER_CREATE', 'Create inventory transfers.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('INVENTORY_MOVEMENT_READ', 'View inventory movements.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('INVENTORY_RECONCILIATION_READ', 'View inventory reconciliation information.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('INVENTORY_RECONCILIATION_EXECUTE', 'Execute inventory reconciliation.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('INVENTORY_LOW_STOCK_READ', 'View low-stock information.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),

-- Warehouse
('WAREHOUSE_READ', 'View warehouse information.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('WAREHOUSE_CREATE', 'Create warehouses.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('WAREHOUSE_UPDATE', 'Update warehouse information.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('WAREHOUSE_DELETE', 'Delete warehouses.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('WAREHOUSE_LOCATION_READ', 'View warehouse locations.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('WAREHOUSE_LOCATION_MANAGE', 'Manage warehouse locations.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('WAREHOUSE_RECEIVING_READ', 'View warehouse receiving operations.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('WAREHOUSE_RECEIVING_MANAGE', 'Manage warehouse receiving operations.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('WAREHOUSE_DISPATCH_READ', 'View warehouse dispatch operations.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('WAREHOUSE_DISPATCH_MANAGE', 'Manage warehouse dispatch operations.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('WAREHOUSE_TRANSFER_READ', 'View warehouse transfers.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('WAREHOUSE_TRANSFER_CREATE', 'Create warehouse transfers.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('WAREHOUSE_TRANSFER_APPROVE', 'Approve warehouse transfers.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('WAREHOUSE_RECONCILIATION_READ', 'View warehouse reconciliation information.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('WAREHOUSE_RECONCILIATION_EXECUTE', 'Execute warehouse reconciliation.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),

-- Invoice / Finance
('INVOICE_READ', 'View invoices.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('INVOICE_CREATE', 'Create invoices.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('INVOICE_UPDATE', 'Update invoices.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('INVOICE_DELETE', 'Delete invoices.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('INVOICE_MATCH_READ', 'View invoice matching information.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('INVOICE_MATCH_EXECUTE', 'Execute invoice matching.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('INVOICE_DISCREPANCY_READ', 'View invoice discrepancies.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('INVOICE_DISCREPANCY_RESOLVE', 'Resolve invoice discrepancies.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('INVOICE_DUE_DATE_READ', 'View invoice due dates.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('INVOICE_DUE_DATE_UPDATE', 'Update invoice due dates.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('INVOICE_PAYMENT_STATUS_READ', 'View invoice payment status.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('INVOICE_PAYMENT_STATUS_UPDATE', 'Update invoice payment status.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('INVOICE_AUDIT_READ', 'View invoice audit information.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),

-- Notification
('NOTIFICATION_READ', 'View notifications.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('NOTIFICATION_CREATE', 'Create notifications.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('NOTIFICATION_UPDATE', 'Update notifications.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('NOTIFICATION_DELETE', 'Delete notifications.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('NOTIFICATION_MARK_READ', 'Mark notifications as read.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),

-- Reporting
('REPORT_READ', 'View available reports.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('REPORT_EXPORT', 'Export reports.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('SPEND_REPORT_READ', 'View spend reports.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('INVENTORY_REPORT_READ', 'View inventory reports.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('PURCHASE_CYCLE_REPORT_READ', 'View purchase cycle reports.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('SUPPLIER_PERFORMANCE_REPORT_READ', 'View supplier performance reports.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('INVOICE_AGEING_REPORT_READ', 'View invoice ageing reports.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('OPERATIONAL_KPI_READ', 'View operational KPIs.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),

-- Audit
('AUDIT_READ', 'View audit records.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('AUDIT_SEARCH', 'Search audit records.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('AUDIT_EXPORT', 'Export audit records.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),

-- AI
('AI_COPILOT_USE', 'Use the application AI copilot.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('AI_SUPPLIER_PERFORMANCE_USE', 'Use AI supplier performance analysis.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('AI_SPEND_ANALYSIS_USE', 'Use AI spend analysis.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('AI_INVENTORY_HEALTH_USE', 'Use AI inventory health analysis.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('AI_INVOICE_AGEING_USE', 'Use AI invoice ageing analysis.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),

-- Security / Access
('ACCESS_REVIEW_READ', 'View access review information.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('ACCESS_REVIEW_EXECUTE', 'Execute access reviews.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('SESSION_REVOKE', 'Revoke active user sessions.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('ACCOUNT_LOCK', 'Lock user accounts.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE),
('ACCOUNT_UNLOCK', 'Unlock user accounts.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, FALSE);
